### ISSUE TITLE
Описать настройку Git в туторе

### ISSUE THREAD

**Issue by Red-Cat-Fat** [LaboratoryOfMedicalCybernetics/RaspberryBrain#3]
Описать настройку Git в туторе, чтобы любой дурак смог повторить и поднять гит сам.

**Comment by nik48rus** [comment]
[Статья о настройке Git'а](https://github.com/LaboratoryOfMedicalCybernetics/RaspberryBrain/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-Git-%D0%BD%D0%B0-Raspberry-Pi)

**Comment by nik48rus** [comment]
Статья в вики является отредактированной версией [этой статьи](http://cccp-blog.com/koding/sozdayom-git-server-svoimi-rukami).

**Comment by nik48rus** [comment]
[Статья про nmap](https://losst.ru/kak-polzovatsya-nmap-dlya-skanirovaniya-seti)

**Comment by Red-Cat-Fat** [comment]
Нужно перенести в репозиторий .md файлами. И написать статью об установке статичного IP

**Comment by nik48rus** [comment]
В написании статьи про установку статического IP использовались [первая](https://dmitrysnotes.ru/raspberry-pi-3-prisvoenie-staticheskogo-ip-adresa) и [вторая](https://losst.ru/tekstovyj-redaktor-nano-v-linux-dlya-novichkov) статья.
